apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: reporting-dapr-secret-store
spec:
  type: secretstores.local.file
  version: v1
  metadata:
    - name: secretsFile
      value: ./components/secrets.json
